<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use Modules\ContractualProcess\Models\InvestmentNeed;
use Faker\Generator as Faker;

$factory->define(InvestmentNeed::class, function (Faker $faker) {

    return [
        'pc_needs_id' => $faker->word,
        'pc_validities_id' => $faker->word,
        'pc_name_projects_id' => $faker->word,
        'dependencias_id' => $faker->word,
        'pc_management_unit_id' => $faker->word,
        'users_id' => $faker->word,
        'pc_project_lines_id' => $faker->word,
        'pc_poir_id' => $faker->word,
        'code_bppiepa' => $faker->word,
        'date_presentation' => $faker->date('Y-m-d H:i:s'),
        'update_date' => $faker->date('Y-m-d H:i:s'),
        'responsible_user' => $faker->word,
        'municipal_development_plan' => $faker->word,
        'period' => $faker->word,
        'strategic_line' => $faker->word,
        'sector' => $faker->word,
        'program' => $faker->word,
        'subprogram' => $faker->word,
        'other_planning_documents' => $faker->text,
        'which_other_document' => $faker->text,
        'description_problem_need' => $faker->text,
        'project_description' => $faker->text,
        'justification' => $faker->text,
        'background' => $faker->text,
        'general_objective' => $faker->text,
        'overall_goal' => $faker->text,
        'general_baseline' => $faker->text,
        'cost_units' => $faker->word,
        'replacement' => $faker->word,
        'expansion' => $faker->word,
        'rehabilitation' => $faker->word,
        'coverage' => $faker->word,
        'continuity' => $faker->word,
        'irca_water_quality_risk_index' => $faker->word,
        'micrometer' => $faker->word,
        'ianc_unaccounted_water_index' => $faker->word,
        'ipufi_loss_index_billed_user' => $faker->word,
        'icufi_index_water_consumed_user' => $faker->word,
        'isufi_supply_index_billed_user' => $faker->word,
        'ccpi_consumption_corrected_losses' => $faker->word,
        'pressure' => $faker->word,
        'discharge_treatment_index' => $faker->word,
        'tons_bbo_removed' => $faker->word,
        'tons_sst_removed' => $faker->word,
        'operational_claim_index' => $faker->word,
        'commercial_claim_index' => $faker->word,
        'efficiency_collection' => $faker->word,
        'via_aqueduct_sewerage_rates' => $faker->word,
        'cleaning_fee_resources' => $faker->word,
        'regalias' => $faker->word,
        'general_participation_system' => $faker->word,
        'decentralized_entity' => $faker->word,
        'capital_contributed' => $faker->word,
        'contributed_capital_official' => $faker->word,
        'capital_contributions' => $faker->word,
        'third_party_contributions' => $faker->word,
        'national_debt' => $faker->word,
        'foreign_debt' => $faker->word,
        'social' => $faker->text,
        'environmental' => $faker->text,
        'economical' => $faker->text,
        'jobs_to_generate' => $faker->text,
        'requires_environmental_license' => $faker->word,
        'license_number' => $faker->word,
        'expedition_date' => $faker->date('Y-m-d H:i:s'),
        'state' => $faker->word,
        'created_at' => $faker->date('Y-m-d H:i:s'),
        'updated_at' => $faker->date('Y-m-d H:i:s'),
        'deleted_at' => $faker->date('Y-m-d H:i:s')
    ];
});
